version: "3.3"
services:
    www:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/share/nginx/html
        ports: 
            - "8080:80"
